# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_secao', models.CharField(max_length=2, verbose_name='Cod. Se\xe7\xe3o')),
                ('secao', models.CharField(max_length=100, verbose_name='Se\xe7\xe3o')),
                ('cod_grupo', models.CharField(max_length=4, verbose_name='Cod. Grupo')),
                ('grupo', models.CharField(max_length=100, verbose_name='Grupo')),
                ('cod_subgrupo', models.CharField(max_length=6, verbose_name='Cod. Subgrupo')),
                ('subgrupo', models.CharField(max_length=100, verbose_name='Subgrupo')),
                ('cod_familia', models.CharField(max_length=9, unique=True, verbose_name='Cod. Familia')),
                ('familia', models.CharField(max_length=100, verbose_name='Familia')),
            ],
            options={
                'ordering': ['cod_familia'],
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_material', models.CharField(max_length=20, unique=True, verbose_name='Cod. Material')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
            ],
            options={
                'ordering': ['material'],
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selecionado', models.BooleanField(verbose_name='Selecionado')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Familia', verbose_name='Familia')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Material', verbose_name='Material')),
            ],
            options={
                'ordering': ['material', 'familia'],
                'verbose_name': 'Sugest\xe3o de Familias',
                'verbose_name_plural': 'Sugest\xf5es de Familias',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sugestao',
            unique_together=set([('material', 'familia')]),
        ),
    ]
