# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugestao',
            options={'ordering': ['material', 'score'], 'verbose_name': 'Sugest\xe3o de Familias', 'verbose_name_plural': 'Sugest\xf5es de Familias'},
        ),
        migrations.AddField(
            model_name='sugestao',
            name='score',
            field=models.FloatField(default=0, verbose_name='Pontua\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
