# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_auto_20160121_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugestao',
            options={'ordering': ['material', '-score'], 'verbose_name': 'Sugest\xe3o de Familias', 'verbose_name_plural': 'Sugest\xf5es de Familias'},
        ),
        migrations.AddField(
            model_name='material',
            name='familia_selecionada',
            field=models.BooleanField(default=False, verbose_name='Familis selecionada'),
        ),
    ]
