# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_auto_20160121_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='cod_familia',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cod. Familia'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cod_grupo',
            field=models.CharField(max_length=5, verbose_name='Cod. Grupo'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cod_secao',
            field=models.CharField(max_length=3, verbose_name='Cod. Se\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cod_subgrupo',
            field=models.CharField(max_length=7, verbose_name='Cod. Subgrupo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='familia_selecionada',
            field=models.BooleanField(default=False, verbose_name='Familia selecionada'),
        ),
    ]
