# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_auto_20160121_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='cod_familia',
            field=models.CharField(max_length=9, unique=True, verbose_name='Cod. Familia'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cod_grupo',
            field=models.CharField(max_length=4, verbose_name='Cod. Grupo'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cod_secao',
            field=models.CharField(max_length=2, verbose_name='Cod. Se\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cod_subgrupo',
            field=models.CharField(max_length=6, verbose_name='Cod. Subgrupo'),
        ),
    ]
