# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_auto_20160121_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='cod_secao',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='secao',
        ),
        migrations.AddField(
            model_name='material',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default.Familia', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='material',
            name='familia_sugerida',
            field=models.BooleanField(default=False, verbose_name='Familia selecionada'),
        ),
        migrations.AddField(
            model_name='material',
            name='multiplas_familias_selecionadas',
            field=models.BooleanField(default=False, verbose_name='Multiplas Familias selecionadas'),
        ),
    ]
