# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_auto_20160121_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_secao', models.CharField(max_length=2, unique=True, verbose_name='Cod. Se\xe7\xe3o')),
                ('secao', models.CharField(max_length=100, verbose_name='Se\xe7\xe3o')),
            ],
            options={
                'ordering': ['cod_secao'],
                'verbose_name': 'Se\xe7\xe3o',
                'verbose_name_plural': 'Se\xe7\xf5es',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='secao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rel_secao', to='default.Familia', verbose_name='Se\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familia',
            name='secao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='default.Secao', verbose_name='Se\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
