# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_auto_20160128_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugestao',
            options={'ordering': ['familia', 'material'], 'verbose_name': 'Sugest\xe3o de Familias', 'verbose_name_plural': 'Sugest\xf5es de Familias'},
        ),
        migrations.AddField(
            model_name='material',
            name='secoes_possiveis',
            field=models.CharField(default='', max_length=100, verbose_name='Se\xe7\xf5es Possiveis'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sugestao',
            unique_together=set([('familia', 'material')]),
        ),
    ]
