# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0010_auto_20160202_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='secoes_possiveis',
            field=models.CharField(default='', max_length=100, verbose_name='Se\xe7\xf5es Possiveis'),
        ),
    ]
