# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0012_auto_20160202_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoSAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_secao', models.CharField(max_length=2, unique=True, verbose_name='Cod. Se\xe7\xe3o')),
                ('secao', models.CharField(max_length=100, verbose_name='Se\xe7\xe3o')),
            ],
            options={
                'ordering': ['cod_secao'],
                'abstract': False,
                'verbose_name': 'Se\xe7\xe3o',
                'verbose_name_plural': 'Se\xe7\xf5es',
            },
        ),
    ]
