# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0014_auto_20160203_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='secao_SAP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.SecaoSAP', verbose_name='Se\xe7\xe3o SAP'),
        ),
    ]
