# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0015_material_secao_sap'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='familia_em_sugeridas',
            field=models.BooleanField(default=False, verbose_name='Familia em Sugeridas'),
        ),
    ]
