# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0016_material_familia_em_sugeridas'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='relevante',
            field=models.BooleanField(default=False, verbose_name='Relevante'),
        ),
    ]
