# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0017_material_relevante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100, unique=True, verbose_name='Setor')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.Familia', verbose_name='Familia'),
        ),
        migrations.AlterField(
            model_name='material',
            name='secao_SAP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.SecaoSAP', verbose_name='Se\xe7\xe3o SAP'),
        ),
        migrations.AddField(
            model_name='secao',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.Setor', verbose_name='Se\xe7\xe3o'),
        ),
    ]
