# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0018_auto_20160216_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_secao', to='default.Secao', verbose_name='Se\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='secao',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.Setor', verbose_name='Setor'),
        ),
    ]
