# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0020_auto_20160512_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familia',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secao',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secaosap',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secaosap',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sugestao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sugestao',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Se\xe7\xf5es Novas Possiveis'),
            preserve_default=False,
        ),
    ]
